### ISSUE TITLE
Add support for AWS Batch launch templates

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision-aws#11]
This issue was copied over from the old version of this repo which has been deleted.

Hector: Blocked by https://github.com/terraform-providers/terraform-provider-aws/issues/6454

Jean: Launch templates are supported in CloudFormation, so we could use them in https://github.com/azavea/raster-vision-cloudformation. Would this allow us to remove the AMI creation steps from the project setup?

Hector: I think we determined that the answer is no, because we still need to apply: https://github.com/azavea/raster-vision-aws/blob/master/packer/scripts/configure-gpu.sh

**Comment by hectcastro** [comment]
I believe that this is unblocked because the resources to use launch templates with Batch exist in CloudFormation (still WIP in Terraform). It doesn't get us around AMI creation, but it does open the door to ad-hoc customization via `cloud-config`.
