### ISSUE TITLE
Consolidate repo with raster-vision-cloudformation

### ISSUE THREAD

**Issue by jeancochrane** [azavea/raster-vision-aws#18]
We've done a good amount of work in https://github.com/azavea/raster-vision-cloudformation to make this repo easier to use. We should consolidate these two repos, since they're aiming at the same purpose.

**Comment by jeancochrane** [comment]
Some changes that I assume to be encapsulated by this issue:

* Either bring code from the new repo in here, or make `raster-vision-cloudformation` the canonical repo
    * `raster-vision-cloudformation` is a fork of this repo, so it should be pretty simple to merge it back in here if that's the direction we choose to go with
* Remove `terraform` directory
* Update `Makefile` to remove Terraform commands
* Update `settings.mk.template` to remove Terraform-specific variables
* Update `README.md` to remove section about deploying with Terraform

**Comment by lewfish** [comment]
I am planning on taking on this task soon.
