### ISSUE TITLE
Circular logic in settings/makefile

### ISSUE THREAD

**Issue by drewbo** [azavea/raster-vision-aws#3]
The makefile requires `settings.mk` to run but one of the values `AMI_ID` in the settings file is set by running the makefile.

**Comment by lewfish** [comment]
Hi Drew! You only need to enter the `AWS_BATCH_BASE_AMI` to run `make create-image`. Once that is done, it will print the AMI id. Then you can enter `AMI_ID` and the other variables and run other make targets like `make plan`.

**Comment by lossyrob** [comment]
We should make this clear in the README, or maybe have two separate `settings.mk` files.
