### ISSUE TITLE
Problems with Batch setup

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision-aws#6]
### Current Workflow

A team of developers at Azavea run Raster Vision experiments using Batch. At some point, someone ran the scripts in `raster-vision-aws` to create some shared Batch resources including a compute environment and job queue. The Terraform state was only stored locally. When a developer makes a branch off of RV and wants to test it on Batch they:
* build a `raster-vision-gpu` image locally that has their changes to Raster Vision baked into it
* run `make publish-container` in the `raster-vision-aws` repo to publish their local `raster-vision-gpu` image to ECR under a personal tag so it can be used on Batch. To do this, they use a personal job definition which points to a personal ECR tag. Each developer has created their own job definitions using the Batch console to accomplish this.

### Problems

1. The mechanism for creating personal job defs is not incorporated into the `raster-vision-aws` Terraform setup. However, after reading Batch docs, it seems like **we could just have Raster Vision override the Docker image tag when jobs are submitted**. Then there is no need for developers to have their own job defs. I'm not sure why we didn't think of this before. https://docs.aws.amazon.com/cli/latest/reference/batch/submit-job.html
2. Even if developers can use a shared job def, I think there is value in having individual job queues and compute environments. This is mostly so that we don't need to sort through other people's jobs when using the console. There have also been occasions when someone wanted to experiment with a different Batch setup (for instance trying a different instance type or setting a different minimum number of VCPUs to keep instances running between job failures) without affecting other people's jobs.
3. Even if some Batch resources should be tied to specific users, there seems to be some common resources (Rocky mentioned the VPC) which should be shared across users. Because of this, the Terraform state should be stored remotely.
4. The `raster-vision-aws` repo seems to have wide applicability beyond users of Raster Vision. I would like to make it more generic so that anyone wanting to run jobs on GPUs on Batch can use it. (See https://github.com/azavea/azavea-10-percent-time/issues/260) This isn't strictly necessary, but it seems like we should replace the many hard-coded references to Raster Vision with a variable that can be set based on the name of the project. Then the repo could be re-named `batch-gpu-setup` or something like that. The alternative is to create a fork of `raster-vision-aws` intended for more general usage, which would allow the two repos to diverge and target different use cases. Of course, this means we'd have to maintain two repos instead of one which is undesirable.

**Comment by lewfish** [comment]
cc: @lossyrob @rbreslow @hectcastro

**Comment by hectcastro** [comment]
Thanks for writing this up. I'm going to hijack the issue so that we can add it to our sprint and use it as a place to add notes. After we work on it, we'll schedule a meeting to discuss next steps.

**Comment by hectcastro** [comment]
I took a pass at the Terraform project and put together the list of comments below. In addition to these, we can also take a look at breaking out tasks for having a central job definition that has support for overrides (container image, etc.), or not (if we decide that is an Azavea specific customization that doesn't make sense in this repository).

I'll also say that I found myself comparing this Terraform project to a Terraform module a few times. Going down the module route may make more sense if we really want a reusable core that external folks can consume. That would also give us a way to reuse that same core in something more specific to our internal goals.

Downsides to that are that we'd have to put a lot more thought into API design, and make more opinionated decisions about what goes into the module and what the user of it needs to provide.

Either way, I like the idea of doing it as a project to start. That should help us get a better feel for what would and wouldn't be necessary in a Terraform module.

**Comments**

- I think that we can remove VPC creation entirely; we can depend on AWS accounts having default VPCs configured
- Can also move all operation into public subnets, which eliminates need for NAT gateways (lower cost, no need for EIPs)
- Avoid taking AZs as input, instead take VPC ID or list of subnet IDs; helps avoid rate limit issues in spot fleet when instance types are not available in all AZs (P3)
- https://github.com/terraform-providers/terraform-provider-aws/issues/6454 has the potential to get us out of creating custom batch AMIs; no PR yet, and thus not baked into an AWS provider release
- Adopt STRTA (`infra`, `cipublish`, `cibuild`, etc.)
- Adopt some form of configurable remote state

**Comment by hectcastro** [comment]
Closing this in favor of the smaller issues we created today:

- https://github.com/azavea/raster-vision-aws/issues/7
- https://github.com/azavea/raster-vision-aws/issues/8
- https://github.com/azavea/raster-vision-aws/issues/9
- https://github.com/azavea/raster-vision-aws/issues/10
- https://github.com/azavea/raster-vision-aws/issues/11
- https://github.com/azavea/raster-vision-aws/issues/12
- https://github.com/azavea/raster-vision-aws/issues/13
