### ISSUE TITLE
Add support for Terraform remote state backed by S3

### ISSUE THREAD

**Issue by hectcastro** [azavea/raster-vision-aws#7]
- Make state bucket parameterized
- Add support for optional prefixing within parameterized bucket
- Add some support for bootstrapping the remote state bucket outside of Terraform (can this realistically be done within Terraform?)

**Comment by jeancochrane** [comment]
Moving this back to the backlog while we prototype a new approach in #16.

**Comment by lewfish** [comment]
Sounds like we don't need this anymore now that we are switching to using Cloudformation
